### ISSUE TITLE
Unknown host repository-estatio.forge.cloudbees.com - Apache isis

### ISSUE THREAD

**Issue by sathiya-dev** [incodehq/incode-platform#108]
I have been using apache isis for creating webservices. Today, when I tried to deploy a webservice developed using apache isis in my machine I am facing the below issue

**_Could not resolve dependencies for project com.abc:section-mapper-webapp:war:1.0-SNAPSHOT: Failed to collect dependencies at org.isisaddons.module.togglz:isis-module-togglz-glue:jar:1.13.0 -> org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Failed to read artifact descriptor for org.isisaddons.module.settings:isis-module-settings-dom:jar:1.13.0-SNAPSHOT: Could not transfer artifact org.isisaddons.module.settings:isis-module-settings-dom:pom:1.13.0-SNAPSHOT from/to Cloudbees snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/): repository-estatio.forge.cloudbees.com: Unknown host repository-estatio.forge.cloudbees.com_**

The repository seems to have been moved. I checked for an alternate repository to use togglz and I couldn't find any other.

**Comment by pqant** [comment]
I've also getting similar error message.  @danhaywood  http://repository-estatio.forge.cloudbees.com/snapshot/ is not accessible right now. is it a temporary error or something else? 

**Failed to execute goal on project app: Could not resolve dependencies for project com.temp:app:war:2: Cannot access cloudbees.estatio.snapshots (http://repository-estatio.forge.cloudbees.com/snapshot/) in offline mode and the artifact org.apache.isis.core:isis-core-webserver:jar:1.16.2 has not been downloaded from it before. -> [Help 1]**

**Comment by danhaywood** [comment]
Apologies for this, a stale configuration.  The repo moved to: https://repo.incode.cloud/

Also, be aware that we're in the process of incorporating the incode-platform over into Apache Isis itself, as part of v2 migration on top of Spring Boot.
