### ISSUE TITLE
Incode Platform build fails at the Integration tests

### ISSUE THREAD

**Issue by jamesagada** [incodehq/incode-platform#14]
This is the test report --

-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$Create
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.294 sec - in domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$Create
-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$ListAll
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE! - in domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$ListAll
happyCase(domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$ListAll)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V
        at domainapp.modules.simple.integtests.tests.SimpleObjectMenu_IntegTest$ListAll.happyCase(SimpleObjectMenu_IntegTest.java:43)

-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusId
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.782 sec <<< FAILURE! - in domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusId
should_be_populated(domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusId)  Time elapsed: 0.034 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusVersionTimestamp
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusVersionTimestamp
should_be_populated(domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$DataNucleusVersionTimestamp)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Name
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Name
accessible(domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Name)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

not_editable(domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Name)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

-------------------------------------------------------------------------------
Test set: domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Title
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 sec <<< FAILURE! - in domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Title
interpolatesName(domainapp.modules.simple.integtests.tests.SimpleObject_IntegTest$Title)  Time elapsed: 0 sec  <<< ERROR!
"tests.txt" 53L, 4999C

**Comment by danhaywood** [comment]
Hmm, the error is "java.lang.NoSuchMethodError":

org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

In 1.15.1 this changed to return <T>:

https://github.com/apache/isis/commit/3076e5b796e30005f536eb8bcdd24b3f4ddca9b3#diff-8196527afd1ca8e3811cb1d65dcc931d

Looks like this causes the issue when running the quickstart against this version.  

The stack trace I see is:

````

java.lang.NoSuchMethodError: org.apache.isis.applib.services.repository.RepositoryService.persist(Ljava/lang/Object;)V

	at org.incode.module.fixturesupport.dom.data.DemoData$Util.persist(DemoData.java:35)
	at org.incode.module.fixturesupport.dom.data.DemoData$Util.persist(DemoData.java:28)
	at domainapp.modules.simple.fixture.scenario.data.SimpleObject_data.persistUsing(SimpleObject_data.java:34)
````

so it's the fixturesupport library (still linked to 1.15.0 version of this API) that's failing.

The fix is to either (a) run against Isis 1.15.0, or (b) wait til I've released 1.15.1 of the incode platform which is linked to run against Isis 1.15.0

Thanks for reporting this.
